//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesList
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MoviesDbEntities : DbContext
    {
        public MoviesDbEntities()
            : base("name=MoviesDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MST_DIRECTOR> MST_DIRECTOR { get; set; }
        public DbSet<MST_MOVIE> MST_MOVIE { get; set; }
        public DbSet<TRANSACTION_MOVIE> TRANSACTION_MOVIE { get; set; }
    
        public virtual ObjectResult<SP_JOIN_MOVIE_Result> SP_JOIN_MOVIE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_JOIN_MOVIE_Result>("SP_JOIN_MOVIE");
        }
    }
}
